### PR TITLE
Add sicher-surfen-de dnscrypt resolver

### PR DESCRIPTION
**Pull request by mmack**
We maintain a anycast dnscrypt network to achieve low-latency.
DNSCrypt server. Non-logging, non-filtering, DNSSEC.

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi Max,

And thanks for this addition!

Looks like there are some reliability issues. GitHub CI cannot connect to it: https://github.com/DNSCrypt/dnscrypt-resolvers/runs/2688532847?check_suite_focus=true#step:3:29

And I can't reach it from my location either.

Can you check on your end?

**Comment by mmack** [comment]
@jedisct1 yeah we have routing issues with the hoster atm, i keep you updated...

**Comment by mmack** [comment]
@jedisct1 can you try again please? We fixed the problems... (fingers crossed :) )

**Comment by jedisct1** [comment]
Looks like everything is working perfectly now!

Good job, and thanks a lot for running this resolver!

**Comment by AnthonyHerman** [comment]
This resolver is either suffering from issues or performing blacklisting. I had to blacklist this resolver in my config after some big sites like amazon.com, google.com, etc. stopped resolving.

**Comment by jedisct1** [comment]
> This resolver is either suffering from issues or performing blacklisting. I had to blacklist this resolver in my config after some big sites like amazon.com, google.com, etc. stopped resolving.

Appears to be working fine here. Can you confirm that you are referring to `sicher-surfen-de`?

**Comment by AnthonyHerman** [comment]
I can also confirm it is working at the moment. Either it is resolved or is transient.

**Comment by mmack** [comment]
@AnthonyHerman we didn't had any issues we're aware off... If you have any problems please do not hesitate to send us some logs... 
For the record: There's no blocking... 
I want to shop on amazon myself :)

**Pull request merged**
