### PR TITLE
qag.me is back

### PR DESCRIPTION
**Pull request by cruisemaniac**
DNSCrypt resolver for Bangalore is back with a new machine and complete opendns upstreaming :-)

### CODE REVIEW

**Comment by jedisct1** [comment]
Yay!

But "no logging" can't really apply if you are forwarding everything to Cisco.

**Comment by cruisemaniac** [comment]
No logging === I do not log. Is there a better way to approach this problem?

**Comment by jedisct1** [comment]
You don't, but they do, and share the data with other companies, and sell access to them.

Hiding the client IP address is not enough for decent privacy. Leaked queries for private host names is already quite sensitive data that shouldn't be recorded by third parties.

If running your own resolver is an issue, maybe choose `1.1.1.1` instead, that has better privacy claims?

**Comment by ashwinmt** [comment]
@jedisct1 `1.1.1.1` is a valid point. Can you point me to running my own resolver? I find it slightly scary to do so. I do need an upstream somewhere? Or do you suggest I handle domain Xfers as well on my own?

**Comment by ashwinmt** [comment]
@jedisct1 updated the upstream to 1.1.1.1 and have also reflected corresponding changes to the text in the PR. Let me know if this makes sense...

**Comment by publicarray** [comment]
> Can you point me to running my own resolver?

I suggest using the docker image, here is a how-to on Scaleway: https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes
And one on vultr.com: https://github.com/jedisct1/dnscrypt-proxy/wiki/DNSCrypt-server-with-vultr.com

Shameless plug: (Recommended only if you have a bit of experience with docker). I've implemented a slightly more complex infrastructure with both dnscrypt and doh protocols: https://github.com/publicarray/dns-resolver-infra it is based on the earlier mentioned docker image.

**Comment by cruisemaniac** [comment]
I will do the dnscrypt server in a few days then. When my bandwidth and cpu limitations are much better known. Till then, can this PR be merged so people can use my server as well?

**Comment by jedisct1** [comment]
Merged!

**Comment by cruisemaniac** [comment]
@publicarray I did setup the dnscrypt server. That is what the pull request was about. Maybe I jumped the gun on my response. My question however is to understand if I can setup a server that doesnt log all the way upstream. The DNSCrypt server (docker based - as built by @jedisct1 ) does still need an upstream DNS resolver to handle queries for records it doesnt have.

Who's on the list that I can add to this upstream (`nameserver` entry in `/etc/resolv.conf`) that does not log any queries? According to the PR that @jedisct1 (Thank you my kind sir) has merged, my upstream is `1.1.1.1` (Cloudflare)

What am I missing in this equation? Is there something about the whole DNS circuitry that I've grossly misunderstood? Please help me here.

Thanks,
@cruisemaniac.

**Comment by jedisct1** [comment]
> The DNSCrypt server (docker based - as built by @jedisct1 ) does still need an upstream DNS resolver to handle queries for records it doesnt have.

Not at all.

It resolves everything from the root servers. You don't need any upstream server.

You can install any DNS resolver such as Knot Resolver or Unbound to get the same result.

**Comment by cruisemaniac** [comment]
Okay, wait... My understanding of this setup is pretty flawed then. So, what do I need the /etc/resolv.conf in the docker container for? I need to revisit the source code then! Also, when I setup unbound, what does the forward-addr refer to here?

**Comment by jedisct1** [comment]
The `/etc/resolv.conf` file may be useful for commands used within the container, such as `apt-get install`.

**Comment by jedisct1** [comment]
If you setup Unbound, you can use `forward-addr` to send everything to an upstream server, but you don't need to use `forward-addr`. Just remove the line. That's what that upstream server did.

**Comment by cruisemaniac** [comment]
@jedisct1 noted. Thanks.

**Pull request merged**
