### PR TITLE
dnscrypt.me moved

### PR DESCRIPTION
**Pull request by mibere**
- new location (state)
- more CPU cores

### CODE REVIEW

**Comment by jedisct1** [comment]
Moarrrr power, yeah!

**Comment by mibere** [comment]
The previous server is still up and running for some days (until Tuesday) to serve users with _refresh_delay = 72_.

**Comment by mibere** [comment]
@jedisct1 please update https://dnscrypt.info/public-servers/

Please use this description for **dnscrypt.me**

`DNSSEC / no logs / no filter, Germany. http://dnscrypt.me`

**Comment by jedisct1** [comment]
All in one line?

Ok, done :)

**Comment by mibere** [comment]
argh, no :) Keep my commit as it was! The commit is and should be a two liner.

But the description on https://dnscrypt.info/public-servers/ is incorrect, it should be

`DNSSEC / no logs / no filter, Germany. http://dnscrypt.me`

**Pull request merged**
