### PR TITLE
Add dnslow.me DoH server

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Would like to add my dnslow.me project here, though there are still many changes ongoing ;)

Reference:
- https://dnslow.me/
- https://github.com/PeterDaveHello/dnslow.me

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi!

Looks like DNSSEC is not supported:

```text
dnscrypt-proxy -resolve dnscrypt.info
Resolving [dnscrypt.info] using 127.0.0.1 port 53

Resolver      : 172.71.149.54
Lying         : no
DNSSEC        : no, the resolver doesn't support DNSSEC
ECS           : ignored or selective
```

**Comment by PeterDaveHello** [comment]
Hi @jedisct1,

Just want to make sure, this option means the DNS resolver support DNSSEC or not, not enabled and do the validation, right?


I'm not sure why I got a different result from `delv` 

```
$ ./dnscrypt-proxy -resolve dnscrypt.info
Resolving [dnscrypt.info] using [::1] port 53

Resolver      : 130.59.198.81 (sonic.switch.ch.)
Lying         : no
DNSSEC        : no, the resolver doesn't support DNSSEC

Canonical name: dnscrypt.info.

IPv4 addresses: 37.59.238.213
IPv6 addresses: -

Name servers  : recital.ns.c9x.org., free.ns.c9x.org.
DNSSEC signed : no
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : google-site-verification=FTBiPTbSicuzpH8bxUyL30z3qWwKhnnqPXTZ9qvn0ug, v=spf1 a mx ip4:164.132.13.235 ip4:87.98.134.126 ip4:92.222.49.126 ip4:188.165.248.100 ip4:37.59.238.212/30 ip4:137.74.223.232/30 ip4:82.64.197.71 -all
```

```
$ delv dnscrypt.info @::1
; fully validated
dnscrypt.info.          86320   IN      A       37.59.238.213
dnscrypt.info.          86320   IN      RRSIG   A 13 2 604800 20220922001959 20220907224959 21974 dnscrypt.info. 36L3x1wydFj2nlKMY6PYl0fCgCCCH0iOMKCOGtqZrFc8Y5WCDvVw/9H6 oWi4EWOmN93QK5zuEnA55u2/NVtWrg==
dnscrypt.info.          86320   IN      RRSIG   A 13 2 604800 20220922001959 20220907224959 24543 dnscrypt.info. fM27bkrdBWSAqK3Ozy/qpQrY4y6plqy80tg2zXi3qU0Cb2Re01h01F4J kBz07hkaAbfgFyonf1OnaBxdO2Eu+w==
```

**Comment by jedisct1** [comment]
Can you try resolving a non-existent name such as `nonexistent-zone.dnscrypt-test.` ? Is the negative response signed according to `delv`?

**Comment by PeterDaveHello** [comment]
> Can you try resolving a non-existent name such as `nonexistent-zone.dnscrypt-test.` ? Is the negative response signed according to `delv`?

@jedisct1 

```
$ delv nonexistent-zone.dnscrypt-test. @::1
;; resolution failed: ncache nxdomain
; negative response, fully validated
; nonexistent-zone.dnscrypt-test.       600 IN  \-ANY   ;-$NXDOMAIN
; . SOA a.root-servers.net. nstld.verisign-grs.com. 2022091401 1800 900 604800 86400
; . RRSIG SOA ...
; . RRSIG NSEC ...
; . NSEC aaa. NS SOA RRSIG NSEC DNSKEY
; dnp. RRSIG NSEC ...
; dnp. NSEC do. NS DS RRSIG NSEC
```

**Pull request merged**
