### PR TITLE
Add new DoH resolver

### PR DESCRIPTION
**Pull request by pakonda**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you!

**Comment by jedisct1** [comment]
DNSSEC doesn't seem to work properly. In fact, any query with EDNS data seems to be returning some weird thing:

```
drill -D -p 5311 c9x.org @127.0.0.1
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 18987
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; c9x.org.	IN	A

;; ANSWER SECTION:
c9x.org.	43199	IN	A	78.194.219.1

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 1562 msec
;; EDNS: version 0; flags: do ; udp: 4096
;; Data: \# 11 00080007000118005cde31
;; SERVER: 127.0.0.1
;; WHEN: Mon Oct  1 21:19:46 2018
;; MSG SIZE  rcvd: 70
```

**Comment by pakonda** [comment]
I got an ad flag. Please check it again.
thanks.
```
; <<>> DiG 9.13.3 <<>> @127.0.0.1 ku.ac.th +dnssec +multi                            
; (1 server found)                                                                   
;; global options: +cmd                                                              
;; Got answer:                                                                       
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65279                            
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1              
                                                                                     
;; OPT PSEUDOSECTION:                                                                
; EDNS: version: 0, flags: do; udp: 4096                                             
; CLIENT-SUBNET: 110.164.194.0/24/0                                                  
;; QUESTION SECTION:                                                                 
;ku.ac.th.              IN A                                                         
                                                                                     
;; ANSWER SECTION:                                                                   
ku.ac.th.               9051 IN A 158.108.216.5                                      
ku.ac.th.               9051 IN RRSIG A 8 3 10800 (                                  
                                20181006131049 20180922213000 54376 ku.ac.th.        
                                k4sPBujCLAjrslE9i9QZvLH31VYfyA/EYxz9JeuBE1pa         
                                IUy9eLmW5Qk6KrlH0Lpo2oKItQf0yFUdecpPWDhFMY2e         
                                79uQmZ8+3clReqjsL4u4mf1tx3JD2og0PCfYpln8ocGB         
                                WLCa7dqI5zCWASYrth4JXtoIsED8dRksWvd0MIM= )           
                                                                                     
;; Query time: 189 msec                                                              
;; SERVER: 127.0.0.1#53(127.0.0.1)                                                   
;; WHEN: Tue Oct 02 09:08:04 SE Asia Standard Time 2018                              
;; MSG SIZE  rcvd: 248                                                               
```

**Comment by jedisct1** [comment]
Oh, ok, that weird thing is `edns-clientsubnet` information.

Maybe some worth mentioning in the description, as some people may not be comfortable with this and its privacy implications.

**Pull request merged**
