### PR TITLE
setup server ibksturm new

### PR DESCRIPTION
**Pull request by ibksturm**
did new rawinstall my server, so have to generate new secret.key and public.key

### CODE REVIEW

**Comment by publicarray** [comment]
Thanks, FYI you can just copy the files over to the new server. For example with scp.

**Comment by ibksturm** [comment]
> Thanks, FYI you can just copy the files over to the new server. For example with scp.

cool, yar ok, find out how :) cool 
now let's look to STOP the update @jedisct1 @publicarray

**Comment by publicarray** [comment]
It might be too late now but for future reference?

**Comment by ibksturm** [comment]
as i understand its just in time ^^ frank merged some other server... 

and yeah, something new learned 😍

**Comment by publicarray** [comment]
Ah ok I misread the notification. Lucky! Happy to have helped 🤩

**Comment by ibksturm** [comment]
yeah, in german theres a slang / „i-told-you“

can‘t see the forrest ‚cause theres to many trees

**Pull request closed without merging**
