### PR TITLE
add relays for dnscrypt.uk

### PR DESCRIPTION
**Pull request by ianbashford**

### CODE REVIEW

**Comment by jedisct1** [comment]
Sorry for the delay, and thank you!

**Comment by jedisct1** [comment]
Hi Ian,

Some resolvers don't run on the standard port (443).

Here are the ports observed for dnscrypt servers so far:

`443, 553, 853, 1443, 2053, 4343, 4434, 4443, 5353, 5443, 8443, 15353`

The `dnscrypt.uk` relay seems to only allow port 443.

Do you think you could possibly add the other ports?

Cheers!

**Comment by ianbashford** [comment]
Sure -  happy to.
To be clear, is this like adding a few additional ports to docker like:  -p
443:443 -p 553:443 -p 853:443    etc, and opening the firewall
appropriately?

**Comment by ianbashford** [comment]
OK -- it's a bit more than just that as that didn't work -- I'll work on
getting those extra ports exposed too...

**Comment by jedisct1** [comment]
Hi Ian,

No, you don't have to open any additional incoming ports.

Are you using the `dnscrypt-server` image or did you install `encrypted-dns-server` directly?

This is in the encrypted dns server configuration file:

```toml
# Allowed upstream ports
# This is a list of commonly used ports for encrypted DNS services
allowed_ports = [ 443, 553, 853, 1443, 2053, 4343, 4434, 4443, 5353, 5443, 8443, 15353 ]
```

(note that maybe it already works totally fine, I didn't take the time to check, the fact that only port 443 worked using your relay was a comment on reddit)

**Comment by ianbashford** [comment]
I'm using the latest docker image (with the IPV6 mod you just merged).  The
config file is exactly as generated by the init process (that section
below).   Firewalls are allowing connections to 443 only (and the process
is only listening on 443) - there are no outbound rules.    I'll start
investigating, but do you have any clues/ideas where to start looking?

################################
#        Anonymized DNS        #
################################
[anonymized_dns]
# Enable relaying support for Anonymized DNS
enabled = true
# Allowed upstream ports
allowed_ports = [ 443, 553, 853, 1443, 2053, 4343, 4434, 4443, 5353, 5443,
8443, 15353 ]
# Allow all ports >= 1024 in addition to the list above
allow_non_reserved_ports = false
# Blacklisted upstream IP addresses
blacklisted_ips = [  ]

**Comment by jedisct1** [comment]
Hi Ian,

Ok, I tested your relay this morning with `securedns`, that uses port `5353`.

And it worked perfectly.

So, the problem that user reported (https://www.reddit.com/r/dnscrypt/comments/dt2hto/new_dnscryptuk_anonymizers/) has probably nothing to do with this.

All is fine. Sorry for having wasted your time :(

**Comment by ianbashford** [comment]
NP at all.
I meant to setup some monitors for the relays anyway.... I actually hadn’t
considered this scenario so it’s been useful.

Ian

**Comment by privacyguy123** [comment]
Quad9s reolver (using 8443) does not work with these servers as Anonymizers

**Comment by ianbashford** [comment]
I used this configuration and it seems to work -  can you point me to an
example you're seeing that's broken?

server_names = ['quad9-dnscrypt-ip4-filter-pri']
routes = [ {server_name='quad9-dnscrypt-ip4-filter-pri',
via=['anon-v.dnscrypt.uk-ipv4']} ]

Saw this log
[2019-11-08 14:28:09] [NOTICE] Network connectivity detected
[2019-11-08 14:28:09] [NOTICE] Source
[/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
[2019-11-08 14:28:09] [NOTICE] Source [/var/cache/dnscrypt-proxy/relays.md]
loaded
[2019-11-08 14:28:09] [NOTICE] Anonymized DNS: routing
[quad9-dnscrypt-ip4-filter-pri] via [anon-v.dnscrypt.uk-ipv4]
[2019-11-08 14:28:09] [NOTICE] Firefox workaround initialized
[2019-11-08 14:28:09] [NOTICE] Now listening to :53 [UDP]
[2019-11-08 14:28:09] [NOTICE] Now listening to :53 [TCP]
[2019-11-08 14:28:09] [NOTICE] [quad9-dnscrypt-ip4-filter-pri] OK
(DNSCrypt) - rtt: 10ms
[2019-11-08 14:28:09] [NOTICE] Server with the lowest initial latency:
quad9-dnscrypt-ip4-filter-pri (rtt: 10ms)
[2019-11-08 14:28:09] [NOTICE] dnscrypt-proxy is ready - live servers: 1


Server responded
dig www.google.com @192.168.3.13

; <<>> DiG 9.10.6 <<>> www.google.com @192.168.3.13
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61621
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com. IN A

;; ANSWER SECTION:
www.google.com. 599 IN A 172.217.17.100

;; Query time: 59 msec
;; SERVER: 192.168.3.13#53(192.168.3.13)
;; WHEN: Fri Nov 08 14:28:14 GMT 2019
;; MSG SIZE  rcvd: 73

**Comment by privacyguy123** [comment]
It works today yes - please close.

**Comment by ianbashford** [comment]
Great - let me know if you get any more issues.
I’ll get the monitors setup too...

**Pull request merged**
