### PR TITLE
securedns.eu updated

### PR DESCRIPTION
**Pull request by ricklahaye**
Updated:
- ads-securedns
- ads-securedns-ipv6
- securedns-ipv6

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks a lot for the update, Rick!

**Comment by jedisct1** [comment]
Hi Rick,

Do you think it would be possible to change the port number you use for the new servers, so that they are compatible with relaying?

This is the set of ports that existing servers use, and that relays allow forwarding to:

```text
443, 553, 853, 1443, 2053, 4343, 4434, 4443, 5353, 5443, 8443, 15353
```

Would one of these work for you?

**Comment by ricklahaye** [comment]
Sorry about that. Will make new merge request.

**Comment by jedisct1** [comment]
No, my bad, I should document this somewhere.

**Pull request merged**
