### PR TITLE
Added pwoss.org

### PR DESCRIPTION
**Pull request by PwOSS**
Hey

Could you please add us as well?

Thanks
Dan

### CODE REVIEW

**Comment by jedisct1** [comment]
Of course!

You're in!

Thanks for running this resolver and relay, Dan!

**Comment by mibere** [comment]
Is the server working for you?

`[2020-12-20 17:43:43] [NOTICE] [pwoss.org-dnscrypt] TIMEOUT`

**Comment by jedisct1** [comment]
Indeed, the server doesn't look responsive.

@PwOSS can you check what's going on?

**Comment by PwOSS** [comment]
Ups, sorry. I updated the server with reboot, yesterday. For some reason it haven't started. It should work now :)

Thanks
Dan

**Comment by mibere** [comment]
Yes, server is online.

**Pull request merged**
