### PR TITLE
new: [doh-server] dns.circl.lu added (IPv4 and IPv6)

### PR DESCRIPTION
**Pull request by adulau**
Signed-off-by: Alexandre Dulaunoy <a@foo.be>

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi Alex,

Unfortunately, DoH clients don't seem to be able to connect to these.

Both `dnscrypt-proxy` and `dnslookup` fail with

```text
x509: certificate signed by unknown authority
```

Maybe an intermediate certificate is missing in your TLS configuration?

**Comment by jedisct1** [comment]
SSL Labs also reports that the [certificate chain is incomplete](https://www.ssllabs.com/ssltest/analyze.html?d=dns.circl.lu&s=185.194.94.71&latest).

**Comment by adulau** [comment]
Hi Franck,

My fault, I did a typo in the configuration. Sorry. It should be ok ;-)

Cheers and thanks a lot for your work.

**Comment by jedisct1** [comment]
Looks better now 👍 

Are you planning to stick to DigiCert, so that their cert can be pinned with your entries? (see [operational recommendations for DoH servers](https://github.com/jedisct1/doh-server#operational-recommendations))

**Comment by adulau** [comment]
We might change early next year. So that's why I didn't put a CAA records until now.

**Comment by jedisct1** [comment]
No problem, them!

The set of properties in the stamps don't include DNSSEC, but your servers seem to do DNSSEC validation. Is it intentional?

**Comment by adulau** [comment]
Indeed, we have a load-balancing setup for the DNS and there is still one in the pool not doing DNSSEC validation. That's why I didn't check the DNSSEC part.

**Comment by jedisct1** [comment]
...and... you're in!

Thank you for running these resolvers!

**Pull request merged**
