### PR TITLE
Add publicarray-au

### PR DESCRIPTION
**Pull request by publicarray**

### CODE REVIEW

**Comment by jedisct1** [comment]
Yay!

Thank you!

Other OpenNIC resolvers have a name that starts with `opennic-` but this is not really important.

Added, thanks and welcome to this new resolver!

**Comment by publicarray** [comment]
Oh ok 😄

Actually the resolver was in v1 but was removed some time later because I had broken my cert renew script at some point.

**Comment by jedisct1** [comment]
No problem :) Welcome back!

**Comment by publicarray** [comment]
hm the server is having issues, might be best to remove it again

**Comment by publicarray** [comment]
ok I've seemed to have fixed it for now.

**Pull request merged**
