### PR TITLE
add google-ipv6

### PR DESCRIPTION
**Pull request by it-can**

### CODE REVIEW

**Comment by jedisct1** [comment]
The name was already `dns.google`. Looks like you just removed the hash of a certificate :/

**Comment by it-can** [comment]
Is there a good sdns decoder? Got one from npm but it seems dodgy

**Comment by it-can** [comment]
I’ll fix it, will only add ipv6

**Comment by it-can** [comment]
@jedisct1 ok changed the PR so only google-ipv6 is added...

**Comment by jedisct1** [comment]
> Is there a good sdns decoder? Got one from npm but it seems dodgy

You can simply click on the name [here](https://dnscrypt.info/public-servers) :)

Also `dnscrypt-proxy -list -json` will dump the whole list with details as a JSON file.

**Pull request merged**
