### PR TITLE
add dama.no sa-80

### PR DESCRIPTION
**Pull request by euh2**
M  v3/public-resolvers.md

### CODE REVIEW

**Comment by euh2** [comment]
Will look into those failures.

**Comment by jedisct1** [comment]
Hi,

Unfortunately, that server doesn't seem to respond to queries: https://github.com/DNSCrypt/dnscrypt-resolvers/pull/480/checks?check_run_id=2511739335

Are you presently using it?

**Comment by euh2** [comment]
I forgot to restart the server after some testing. Now it should work, I hope!

**Comment by euh2** [comment]
I start over! Wrong sdns..

**Comment by jedisct1** [comment]
Hi!

`dama.no-osl-s04` and `anon-dama.no` seem to be having some trouble.

Can you take a look?

Thanks!

**Pull request closed without merging**
