### PR TITLE
New odoh target:  odoh-koki-se

### PR DESCRIPTION
**Pull request by kokial**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you Alek!

**Comment by jedisct1** [comment]
Looks like there are IPv6 records for `odoh-target.alekberg.net` and `odoh-target-se.alekberg.net`, but the server is not reachable over IPv6.

Can you take a look, or maybe remove the IPv6 record?

**Comment by kokial** [comment]
Thanks.
Is working now ?

**Comment by jedisct1** [comment]
Yes, they look good now!

Thank you!

**Comment by kokial** [comment]
Great !.  Thank you.

**Pull request merged**
