### PR TITLE
v3/relays: add anon-pf

### PR DESCRIPTION
**Pull request by pfactum**
Signed-off-by: Oleksandr Natalenko <oleksandr@natalenko.name>

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi!

Is the IP correct?

It doesn't seem that the relay is working.

**Comment by pfactum** [comment]
@jedisct1 the IP is correct. it seems i've bumped into some issue with UDP fragments and i have no idea what to do. i didn't block them explicitly. do you have any hints on this?

**Comment by pfactum** [comment]
This is what I have:

```
    1 0.000000000 x.x.x.x → 10.0.0.9     IPv4 1514 Fragmented IP protocol (proto=UDP 17, off=0, ID=5ee6)
    2 0.000140435 x.x.x.x → 10.0.0.9     UDP 582 48865 → 8443 Len=540
    3 0.000187935 x.x.x.x → 10.0.0.9     UDP 582 44024 → 8443 Len=540
    4 0.000332128 x.x.x.x → 10.0.0.9     UDP 582 43114 → 8443 Len=540
    5 0.000381510     10.0.0.9 → 51.15.122.250 UDP 554 58754 → 443 Len=512
    6 0.000430233     10.0.0.9 → 51.15.122.250 UDP 554 42361 → 443 Len=512
    7 0.000456111 x.x.x.x → 10.0.0.9     IPv4 1514 Fragmented IP protocol (proto=UDP 17, off=0, ID=5eea)
    8 0.000481119     10.0.0.9 → 51.15.122.250 UDP 554 44238 → 443 Len=512
    9 0.000659045 x.x.x.x → 10.0.0.9     IPv4 1514 Fragmented IP protocol (proto=UDP 17, off=0, ID=5eeb)
   10 0.013933195 51.15.122.250 → 10.0.0.9     UDP 225 443 → 42361 Len=183
   11 0.013933346 51.15.122.250 → 10.0.0.9     UDP 225 443 → 58754 Len=183
   12 0.013967320     10.0.0.9 → x.x.x.x UDP 225 8443 → 44024 Len=183
   13 0.014013367     10.0.0.9 → x.x.x.x UDP 225 8443 → 48865 Len=183
   14 0.014130378 51.15.122.250 → 10.0.0.9     UDP 225 443 → 44238 Len=183
   15 0.014158601     10.0.0.9 → x.x.x.x UDP 225 8443 → 43114 Len=183
   16 31.119948232     10.0.0.9 → x.x.x.x ICMP 590 Time-to-live exceeded (Fragment reassembly time exceeded)
   17 31.119962749     10.0.0.9 → x.x.x.x ICMP 590 Time-to-live exceeded (Fragment reassembly time exceeded)
   18 31.119975302     10.0.0.9 → x.x.x.x ICMP 590 Time-to-live exceeded (Fragment reassembly time exceeded)
```

`x.x.x.x` is `dnscrypt-proxy`, set up to use `scaleway-ams` (_51.15.122.250_) via `anon-pf`. `10.0.0.9` is the VM in the Oracle Cloud that runs `encrypted-dns`. Yes, it's behind that cloud NAT, but port `8443` tcp/udp is open, and non-relay connection works fine.

What else I should look at?

**Comment by pfactum** [comment]
OK, neither stateful not stateless rules on Oracle's side work, so I had to allow all the traffic and rely on VM firewall instead. This way it looks like working now. Will resubmit the PR.

Sorry for the noise.

**Pull request merged**
