### PR TITLE
add johnrosen1

### PR DESCRIPTION
**Pull request by johnrosen1**

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi!

Looks like there is something wrong with that server. Using `dnslookup`:

```sh
dnslookup example.com sdns://AgYAAAAAAAAADDEwMy4zMC4xNy4yMyAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiA5qb2hucm9zZW4xLmNvbQovZG5zLXF1ZXJ5

Cannot make the DNS request: got an unexpected HTTP status code 400 from 'https://johnrosen1.com:443/dns-query'
```

No DNS padding is also a little bit weird. What software are you using? You can use [`doh-server`](https://github.com/jedisct1/doh-server) that handles this.

**Comment by johnrosen1** [comment]
ok,i will try to change that ,sorry

**Comment by johnrosen1** [comment]
image

not quite sure why 400 is happened

**Comment by jedisct1** [comment]
Gave it a new try.

Looks like everything is working perfectly now! 👍

**Comment by jedisct1** [comment]
Oops, looks like you are still testing, as this is forwarding everything to Quad9, not to your resolver.

**Comment by jedisct1** [comment]
Feel free to reopen when you'll be all set! 👍

**Pull request merged**
