### PR TITLE
Add Vietdns DOH Server

### PR DESCRIPTION
**Pull request by tranhoangcore**
This a new DOH dns server in Vietnam.
https://vietdns.vn/

Thank you.

### CODE REVIEW

**Comment by tranhoangcore** [comment]
@jedisct1 Updated.

**Comment by tranhoangcore** [comment]
@jedisct1 `Vietdns` currently only opens routes for some countries such as Vietnam to be used, according to the administrator.

**Comment by jedisct1** [comment]
That should really be added to the description.

Also this is going to break CI and monitoring, so there's a bit of work to make an exception for it :(

**Comment by bigdargon** [comment]
@tranhoangcore Unblocked country, please try again! https://voz.vn/t/vietdns-dns-viet-phien-ban-voz-chan-quang-cao-virut-noi-dung-doc-hai.553969/post-19721768

**Comment by tranhoangcore** [comment]
@bigdargon Ok.
@jedisct1 Can you enable CI again?

**Pull request closed without merging**
