### PR TITLE
Add NixNet DNS resolvers

### PR DESCRIPTION
**Pull request by nitrohorse**
Adds NixNet's DNS resolvers. NixNet is a collection of open source and privacy-focused services maintained by [Amolith](https://social.nixnet.services/@amolith). No logging, QNAME minimisation, DNSSEC, and optional adblocking. https://nixnet.services/

Documentation: https://docs.nixnet.services/DNS
Privacy policy: https://docs.nixnet.services/DNS/Privacy

### CODE REVIEW

**Comment by jedisct1** [comment]
These servers don't support HTTP/2, which is required by the DoH specification :(

**Comment by jedisct1** [comment]
DNSSEC doesn't seem to work either.

**Comment by jedisct1** [comment]
Update: DNSSEC validation is done on `uncensored` versions, but not on the `adblock` ones.

**Comment by nitrohorse** [comment]
Ah interesting, TIL, apologies for the churn and misunderstanding on my part!

**Pull request merged**
