### PR TITLE
Vancouver is here!.

### PR DESCRIPTION
**Pull request by evilvibes**
Added a new server Vancouver and change the Toronto server host. bye bye vultr :(

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks for the update and welcome to the new server in Vancouver!

**Comment by publicarray** [comment]
Hi @evilvibes I'm currently using vultr. I was wondering why you switched?

**Comment by evilvibes** [comment]
Only move for a host that has both locations I wanted. I also I wanted to be paying in CAD not USD. Vultr is great provider wouldn’t of moved if it wasn’t for them reasons. @publicarray

**Comment by publicarray** [comment]
Thanks @evilvibes, Fair enough, I was just just curious. Keep up the good work 👍

**Comment by MystesofEternity** [comment]
I've been getting incorrect signature warnings from your server since like 2-3 weeks ago. Good thing I just remembered to report about this
image

**Comment by evilvibes** [comment]
@MystesofEternity That's odd everything seems to be working from my end. @jedisct1 What could be causing this issue?

**Comment by jedisct1** [comment]
Maybe a timestamp issue? Can you verify that your clock is correct, @MystesofEternity ?

**Pull request merged**
