### PR TITLE
Added an ad/tracker/analytics blocking DNSCrypt server from Hyderabad…

### PR DESCRIPTION
**Pull request by coolquasar**
…, India - Oracle Cloud

### CODE REVIEW

**Comment by jedisct1** [comment]
And you're in!

The resolver is currently named `jitender` but can be set to something else if you prefer.

Thanks for running that resolver!

**Comment by coolquasar** [comment]
Thankyou so much for approving the PR. I wanted to give back to the
community.

Regards
Jitender

**Comment by coolquasar** [comment]
I just noticed that the sdns string does not match the one I checked in. Is
that an intentional change ? Can I checkin the correct version ?

[image: image.png]

**Comment by coolquasar** [comment]
Alright, I just noticed, that the stamp has been re-generated using updated
public key. Please ignore my email

Regards
Jitender

**Comment by jedisct1** [comment]
Indeed, since this is a filtering resolver, the `no filter` flag has been unset. Also the port number (`:443`) has been removed since this is the default port. That saves a few bytes :)

**Comment by coolquasar** [comment]
Thankyou




----------
On Wed, Oct 7, 2020 at 7:57 PM, Frank Denis <notifications@github.com>
wrote:

Indeed, since this is a filtering resolver, the no filter flag has been
unset. Also the port number (:443) has been removed since this is the
default port. That saves a few bytes :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DNSCrypt/dnscrypt-resolvers/pull/348#issuecomment-704974197>,
or unsubscribe

**Pull request merged**
