### PR TITLE
Fusl's resolvers no longer support DNSCrypt

### PR DESCRIPTION
**Pull request by Zenexer**

### CODE REVIEW

**Comment by Zenexer** [comment]
My understanding is that OpenNIC support is also being removed.  doh is being added.

**Comment by jedisct1** [comment]
That's pretty sad :(

**Comment by Zenexer** [comment]
Here's the announcement from @Fusl:

image

**Comment by Fusl** [comment]
Can confirm, please remove, for now at least. Maybe I'll find some time again to fix the bugs that docker and [my auto rollover script](https://github.com/anyqast/uniqast-dnscrypt-wrapper/blob/master/files/dnscrypt-wrapper.sh) introduced but at this time I'm concentrating on getting everything back to more stability.

**Pull request merged**
