### PR TITLE
Update public-resolvers.md

### PR DESCRIPTION
**Pull request by ibksturm**
Add dnscrypt server in Switzerland by ibksturm

### CODE REVIEW

**Comment by jedisct1** [comment]
Fantastic!

Thanks for running that resolver!

It has been added. Thanks!

**Comment by ibksturm** [comment]
your welcome frank

was a long long night... unbound and dnsdist sucked when dnscrypt-wrapper was running...  without i could resolve with dig, activating wrapper it crashes.... don‘t know why.

so i changed on 4:00 to dnsmasq (was a good idear, cause id copy the dnsmasq.conf from my home dns resolver). benefit to all is now, that the standard tld‘s AND the opennic tdl are resolved

so on, could someone give me a feedback from outside how my server is running?
greets

**Comment by publicarray** [comment]
I tried connecting but I seem to get timeouts. I'm curious to know how dnsmasq is setup, because dnsmasq is a forwarding/chache server and dnsdist is a DNS load balanceer. Neither of which have a resolving component.

**Comment by ibksturm** [comment]
hi there :)

now it should work, i forget to write a cron.daily job to renew the certs

to dnsmasq, that's my idear that it works in the backend as forwarder (3x dnscrypt resolver -> 1x opennic, 1x cloudflare, 1x google) and cache server


and here's my config
----------- /etc/dnsmasq.conf -----------
bogus-priv
domain-needed

# Uncomment these to enable DNSSEC validation and caching:
# (Requires dnsmasq to be built with DNSSEC option.)

#dnssec
#conf-file=/etc/dnsmasq/trust-anchors.conf
proxy-dnssec

log-facility=/var/log/dnsmasq/dnsmasq.log

no-resolv

cache-size=2048
local-ttl=3600
max-cache-ttl=3600
min-cache-ttl=60
neg-ttl=60
max-ttl=3600

dns-loop-detect
stop-dns-rebind

#server=1.1.1.1

server=127.0.0.1#854
server=127.0.0.1#855

server=/.glue/127.0.0.1#853
server=/.bbs/127.0.0.1#853
server=/.bit/127.0.0.1#853
server=/.chan/127.0.0.1#853
server=/.dyn/127.0.0.1#853
server=/.free/127.0.0.1#853
server=/.fur/127.0.0.1#853
server=/.geek/127.0.0.1#853
server=/.gopher/127.0.0.1#853
server=/.indy/127.0.0.1#853
server=/.libre/127.0.0.1#853
server=/.neo/127.0.0.1#853
server=/.null/127.0.0.1#853
server=/.opennic.glue/127.0.0.1#853
server=/.oss/127.0.0.1#853
server=/.oz/127.0.0.1#853
server=/.parody/127.0.0.1#853
server=/.pirate/127.0.0.1#853
server=/.o/127.0.0.1#853
server=/.lib/127.0.0.1#853
server=/.coin/127.0.0.1#853
server=/.emc/127.0.0.1#853
server=/.bazar/127.0.0.1#853
server=/.cyb/127.0.0.1#853
server=/.fur/127.0.0.1#853
server=/.ku/127.0.0.1#853
server=/.te/127.0.0.1#853
server=/.uu/127.0.0.1#853
server=/.ti/127.0.0.1#853



server=/.bazar/127.0.0.1#853
server=/.cyb/127.0.0.1#853
server=/.fur/127.0.0.1#853
server=/.ku/127.0.0.1#853
server=/.te/127.0.0.1#853
server=/.uu/127.0.0.1#853
server=/.ti/127.0.0.1#853

expand-hosts
no-hosts

bind-interfaces

all-servers

listen-address=127.0.0.1
listen-address=127.0.1.1
listen-address=192.168.0.191

no-poll

**Comment by publicarray** [comment]
Hi, Thanks for your transparency. Yea cert renewal been there and I still can't get it right sometimes. 
I hope you had a good nights sleep.

Interesting setup. So using your server, queries are dispersed to many different servers. Many of which are already in dnscrypt-proxy's default list? I'm not sure if that is a good idea. dnscrypt-proxy can already be configured to randomly send queries to a chosen server list.

I've never used Bind, good luck! For unbound you can use https://github.com/DNSCrypt/dnscrypt-server-docker as a reference.

**Comment by ibksturm** [comment]
update 

after a night with sleep (yeah thanks, was good) i realised the problem!

i reinstall unbound, configure it and then i figure out, that i forgott to chown unbound:unbound /etc/unbound, so unbound hasn't got the rights to read the root.hints and root.key files.... i changed and now, my structur runs like this


443 - router -- 8543 -- dnscrypt-wrapper -127.0.1.1 - dnsmasq (for caching & resolve opennic domains) 

then 

dnsmasq -- 127.0.0.1:853 dnscrypt-proxy (opennic domains)
dnsmasq -- 127.0.1.2 unbound (and there with the root.hints)

i put my config files for undbound, dnsmasq and 2x files of cron.daily with

[server.zip](https://github.com/DNSCrypt/dnscrypt-resolvers/files/2045978/server.zip)

**Comment by ibksturm** [comment]
@publicarray next question (as on twitter)
do you now how to crypto the upstream querys to the root tdl servers from unbound?

unbound --- *crypto* -- root servers

maybe it's impossible, so i cant find something on google...

**Comment by publicarray** [comment]
Hi, as far as I'm aware there are no authoritative servers (including root) at the moment that run via the encrypted protocols. Both [DNS-over-TLS](https://tools.ietf.org/html/rfc7858) and [DOH](https://tools.ietf.org/html/draft-ietf-doh-dns-over-https) have something like this in their RFC document:

> This document focuses on communication between DNS clients (such as operating system stub 
resolvers) and recursive resolvers.

Same goes for dnscrypt. If you like some more reading material: [https://dnsprivacy.org The Problem](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+-+The+Problem) and [rfc7626](https://tools.ietf.org/html/rfc7626)

It will be a while before authoritative add encryption. This is all very new.

You can however [host your own copy of root](https://tools.ietf.org/html/rfc7706). Just make sure to keep it updated. Alternatively [aggressively using NSEC to return NXDOMAIN responses](https://datatracker.ietf.org/doc/rfc8198/) (`aggressive-nsec: yes`) reduces lookups to root considerably and is what I use currently.

**Comment by ibksturm** [comment]
hi there :) 

a) first greets from liam (sound engineer from perth, living here in switzlerland)

second, update:
last monday evening i sit down und reconfigure my server. now its running without dnsmasq (thanks to your argument) so only unbound 1.7.1 (inclusing dnscrypt) 

i‘m thinking now to disable dnnsec, cause on some configuration at the client side (example dnssec & trust anchord ena le in dnsmasq, not dnssec-proxy) it wouldn resolv the opennic domains

an yes i set on unbound the opennic tlds as unsecure-zone

saddly i didnt got some external feedback about opennic resolv :(

third, thanks to all your documents they become my good night lecture :)

greets

**Comment by publicarray** [comment]
> unsecure-zone

Do you mean something like `domain-insecure: "libre"` for *all* opennic TLDs?

> **domain-insecure:** <domain name>
 Sets domain name to  be  insecure,  DNSSEC  chain  of  trust  is
              ignored  towards  the  domain name.  So a trust anchor above the
              domain name can not make the domain secure  with  a  DS  record,
              such  a  DS  record  is  then  ignored [...]

To see what is going on you can increase logging temporarily:  `unbound-control verbosity 7` and `unbound-control set_option val-log-level: 2`. Remember to set them back to zero to stop.

**Comment by publicarray** [comment]
Ah sorry, I read to fast. Yes the client can't validate opennic TLDs because it doesn't know that it's a different root and thus a different root-anchor. The easiest way to work around this is to do the DNSSEC validation in the resolver and have the client trust the server. You can check [here](https://dnssec.vs.uni-due.de/) if DNSSEC is setup correctly. The resolver should return SRVFAIL when DNSSEC validation fails (except when the `cd` flag is set).
I think in dnsmasq as the client it's the `proxy-dnssec` option that you want to use.

**Comment by publicarray** [comment]
Just a small note. Running two roots side by side like this is a bit of a hack (I do it anyway). Also imagine a situation where a TLD is in both roots (I think `free.` was for a short time, http://nic.free/).

**Comment by ibksturm** [comment]
hi @publicarray 

oki, i will try to hack it too ^^ i will write you if ive got some troubles

**Comment by ibksturm** [comment]
hi sebastion

so on, i tried to run a doh server with haproxy 

software:

1.8.9 (selfcompiled)
rust-doh from git 

------ config -----
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        tune.ssl.default-dh-param 2048
        ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:$
        ssl-default-bind-options no-sslv3 no-tls-tickets
        ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA25$
        ssl-default-server-options no-sslv3

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option  redispatch
        retries 3
        maxconn 2000
        timeout connect 5s
        timeout check 10s
        timeout client 20s
        timeout server 15s

frontend doh_front
   option httplog
   bind *:8543 ssl crt /etc/doh-proxy/ibksturm.synology.me.pem
   http-response set-header Strict-Transport-Security max-age=15768000
   acl rule_doh path_beg -i /dns-query
   use_backend doh_back if rule_doh
   default_backend http_default

backend doh_back
   option forwardfor
   balance roundrobin
   server doh-proxy 192.168.0.XXX:3000

backend http_default
   mode http
   balance roundrobin
   server nas 192.168.0.YYY:80

listen stats
   bind *:8181
   stats enable
   stats uri /
   stats realm Haproxy\ Statistics
   stats auth user:password (allready changed)
*********

doh-proxy -u 192.168.0.191:53 -l 192.168.0.191:3000 -c 256 -p /dns-query
Listening on http://192.168.0.191:3000

-----------

ok so on, on dnsproxy i've got this error

[2018-06-05 02:09:30] [ERROR] Get https://ibksturm.synology.me:8543/dns-query?body=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[2018-06-05 02:09:30] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable

---------- static entry in the .toml file  -----
[static.'doh-ibksturm']
stamp ='sdns://AgcAAAAAAAAADzIxNy4xNjIuMjA2LjE3OAAZaWJrc3R1cm0uc3lub2xvZ3kubWU6ODU0MwovZG5zLXF1ZXJ5'
---------------------------------------

on firewall, all needed ports are open (checked twice)
if i open https://ibksturm.synology.me:8543, my testpage on server 3 comes up, if i ad /dns-query it sucks (Error 400).... i try to switch the server on backend doh_back and it runs....
but that's not the final solution, i want to run doh-proxy in the backend...

any idears or fancy magical wipps to solf my problem?

greets
andi

**Comment by ibksturm** [comment]
update:
i programmed till 5 o'clock in the morning... 
connection between outside thru haproxy till rust-doh runs.... now in the log files was writen, theres troubles with ssl/1 handshake...

**Comment by ibksturm** [comment]
update
i realy realy don't now why, but now it runs... 

_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[2018-06-05 22:07:06] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
[2018-06-05 22:16:27] [NOTICE] [doh-ibksturm] OK (DoH) - rtt: 3ms
[2018-06-05 22:16:27] [NOTICE] Server with the lowest initial latency: doh-ibksturm (rtt: 3ms)


so in the last 2 hours since i edited my post aboufe, i was in the childrens room... creepy shit...
the mainquestion is now, why the hell he got about 10 minutes to connect them?

**Comment by publicarray** [comment]
Can I suggest that you wrap code/config files with a markdown code block like this:

````
```
code here
```
````


> any workaround to test the rust-doh himself?

Try curl: 
```
$ curl 'https://doh.seby.io/dns-query?ct&dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | cat
$ curl 'http://127.0.0.1:3000/dns-query?ct&dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB'  | cat
```
> i realy realy don't now why, but now it runs

Good work  👍 

> why the hell he got about 10 minutes to connect them?

I really don't know, I would try and remove `http/1.1` from the bind setting or I would try and simply the config as much as possible, adding more settings later. It could also be related to the OS. You also can try an analyse the situation with `tcpdump` and capture some packets and open the capture in wireshark.

**Pull request merged**
