### PR TITLE
PR for correct information about faelix.net

### PR DESCRIPTION
**Pull request by maznu**
Hi there, I'm the owner and technical director of faelix.net and as per comments on your commit that added us to this database:

* we don't log on our public resolvers
* we process-not-verify DNSsec (but that'll change in time)
* we don't EDNS Subnet
* we hope to soon QNAME minimise
* much as we love Wales, that's not where our servers are :-)

You're welcome to verify by dropping me an email to firstname at faelix.net.

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks for the update!

Unfortunately, it doesn't seem to work:

```text
certificate is valid for creativeconcern-com.cdn.gofasterstripes.download, qsr-waddensea-worldheritage-org.cdn.gofasterstripes.download, waronwant-org.cdn.gofasterstripes.download, www-waddensea-worldheritage-org.cdn.gofasterstripes.download, not rdns.faelix.net
```

**Comment by jedisct1** [comment]
Looks like it depends on the node it is hitting. `185.134.196.55` doesn't have a certificate for `rdns.faelix.net`.

Also, DNSSEC is not supported:

```sh
$ drill -D dnscrypt.info @127.0.0.1
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 55542
;; flags: qr rd ra ; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
```

No `ad` flag here.

**Comment by maznu** [comment]
> Thanks for the update!
> 
> Unfortunately, it doesn't seem to work:

Problem solved — a wrong "A" record — thanks for the heads-up!

> Also, DNSSEC is not supported:

Ok, I've changed powerdns-recursor from `process-no-validate` to `process` and it's showing up:

```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 23872
;; flags: qr rd ra ad ; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
```

**Comment by jedisct1** [comment]
Looking good!

Thanks for the update!

**Pull request merged**
