### PR TITLE
add easymosdns-doh

### PR DESCRIPTION
**Pull request by UjuiUjuMandan**
As described in the file.

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi!

Since this is not a resolver, but a forwarder that relays queries to untrusted 3rd parties, would it be possible to mention this in the description?

Thanks!

**Comment by jedisct1** [comment]
Hashes are also missing; this is important for DoH security. See https://github.com/DNSCrypt/doh-server#dns-stamp-and-certificate-hashes

**Comment by UjuiUjuMandan** [comment]
I've added upstream information and hashes.

**Comment by UjuiUjuMandan** [comment]
Looks like the action failed, probably because the CDN used by this server doesn't support HTTP/2? 

I confirm the hashed I entered is correct.

**Comment by jedisct1** [comment]
Wait, this is also using Cloudflare as a front-end. That should be mentioned as well. That's a lot of 3rd parties, not sure that the "no log" flag applies here. 

The hash should be removed after all, sorry for the confusion. Cloudflare certs are not the same everywhere, so they can't be pinned.

**Comment by UjuiUjuMandan** [comment]
I didn't know it uses Cloudflare before... I sshed to a oversea VPS and the dig result shows Cloudflare IPs. But here in China it shows a different, local CDN (China Mobile).

```
doh.apad.pro.		120	IN	CNAME	dfb10000.pchome.net.cname.hcnamecdn.com.
dfb10000.pchome.net.cname.hcnamecdn.com. 30 IN A 112.47.52.134
dfb10000.pchome.net.cname.hcnamecdn.com. 30 IN A 117.149.203.53
```

Cloudflare firewall may log queries sometimes, so I will remove the nologs flag.

**Pull request merged**
