### PR TITLE
opennic-R4SAS stamps (dnscrypt, doh, relay)

### PR DESCRIPTION
**Pull request by r4sas**
Returning back with new configuration and DOH support.

### CODE REVIEW

**Comment by jedisct1** [comment]
Yayyyy welcome back! 🎉

**Comment by jedisct1** [comment]
Look like there are some issues over IPv6:

```text
[2021-08-02 22:30:29] [ERROR] read udp [2a01:e0a:1f0:1360:5c86:1f96:f66b:9b94]:52775->[2001:470:1f15:b80::53]:443: i/o timeout
[2021-08-02 22:30:44] [ERROR] read udp [2a01:e0a:1f0:1360:5c86:1f96:f66b:9b94]:60013->[2001:470:1f15:b80::53]:443: i/o timeout
[2021-08-02 22:30:59] [ERROR] read udp [2a01:e0a:1f0:1360:5c86:1f96:f66b:9b94]:51114->[2001:470:1f15:b80::53]:443: i/o timeout
[2021-08-02 22:31:14] [ERROR] read udp [2a01:e0a:1f0:1360:5c86:1f96:f66b:9b94]:53730->[2001:470:1f15:b80::53]:443: i/o timeout
FAIL: anon-opennic-R4SAS-ipv6 (sdns://gRtbMjAwMTo0NzA6MWYxNTpiODA6OjUzXTo0NDM)
```

```text
2021/08/02 22:35:53 Cannot make the DNS request: couldn't do a GET request to 'https://opennic.i2pd.xyz:443/dns-query', cause: Get "https://opennic.i2pd.xyz:443/dns-query?dns=Kk8BAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE": context deadline exceeded
```

Can you check that the server has IPv6 connectivity?

**Comment by r4sas** [comment]
That's strange, that you can't connect to server:
```
[2021-08-02 22:39:29] [NOTICE] dnscrypt-proxy 2.0.46-beta3
[2021-08-02 22:39:29] [NOTICE] Network connectivity detected
[2021-08-02 22:39:29] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2021-08-02 22:39:29] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2021-08-02 22:39:29] [NOTICE] Source [opennic] loaded
[2021-08-02 22:39:29] [NOTICE] Source [public-resolvers] loaded
[2021-08-02 22:39:29] [NOTICE] Source [relays] loaded
[2021-08-02 22:39:29] [NOTICE] Source [odoh] loaded
[2021-08-02 22:39:29] [NOTICE] Firefox workaround initialized
[2021-08-02 22:39:34] [NOTICE] [opennic-R4SAS-ipv6] OK (DNSCrypt) - rtt: 60ms
[2021-08-02 22:39:34] [NOTICE] [opennic-R4SAS-doh-ipv6] OK (DoH) - rtt: 59ms
[2021-08-02 22:39:35] [NOTICE] [opennic-R4SAS] OK (DNSCrypt) - rtt: 67ms
[2021-08-02 22:39:35] [NOTICE] [opennic-R4SAS-doh] OK (DoH) - rtt: 60ms
[2021-08-02 22:39:35] [NOTICE] Sorted latencies:
[2021-08-02 22:39:35] [NOTICE] -    59ms opennic-R4SAS-doh-ipv6
[2021-08-02 22:39:35] [NOTICE] -    60ms opennic-R4SAS-ipv6
[2021-08-02 22:39:35] [NOTICE] -    60ms opennic-R4SAS-doh
[2021-08-02 22:39:35] [NOTICE] -    67ms opennic-R4SAS
```

**Comment by r4sas** [comment]
@jedisct1 have you tried again? I haven't any issues from beginning.

**Comment by jedisct1** [comment]
Still unreachable from here:

```sh
$ doggo example.com @sdns://AQcAAAAAAAAAG1syMDAxOjQ3MDoxZjE1OmI4MDo6NTNdOjQ0MyCp1jI6TyWACSYZdRUCziMeH3bZ3ndsh8a7sooO_9sOTiAyLmRuc2NyeXB0LWNlcnQub3Blbm5pYy5pMnBkLnh5eg
```

```text
ERROR[2021-08-13T12:20:26+02:00] error loading resolver                        error="read udp [2a01:e0a:1f0:1360:559d:3a2e:c3eb:f0cb]:52927->[2001:470:1f15:b80::53]:443: i/o timeout"
```

**Comment by r4sas** [comment]
Really strange. I'll ask Hurricane Electric support.

**Comment by jedisct1** [comment]
Traceroute is quite minimal:

```text
 2  2a01:e00:2041:f836:8a2f::ffff  4.176 ms  4.938 ms  4.127 ms
 3  2a01:e00:2041:1700::ffff  3.157 ms  3.301 ms  3.575 ms
 4  2a01:e00:2041::2  4.688 ms  4.880 ms  8.855 ms
 5  * * *
 6  2a01:e00:2044::5  5.779 ms  3.542 ms  4.253 ms
 7  * * *
 8  * * *
 9  * * *
```

**Comment by r4sas** [comment]
Looks like problem between networks, can't reach your network using Looking Glass service provided by HE. Reported.

**Comment by r4sas** [comment]
@jedisct1
Response from HE:
>Hello,
>
>The destination network is available only through AS174 Cogent. Currently, we do not share any IPv6 connectivity with AS174, >and thus, this route is expected to fail.

**Comment by jedisct1** [comment]
Wow. So some IPv6 networks are only reachable from a subset of other IPv6 networks?

Not great :(

**Comment by r4sas** [comment]
So maybe you'll add ipv6 entries to master?

**Pull request merged**
